### ISSUE TITLE
Error from stack_detector_data

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#123]
Dear experts,
with karabo_data version 3.0, I run (1) but I got the error message (2). I used a run in the cxidb with ID-80 and ID-83 (3). Do you see what is wrong?
Regards

(1)
tid, train_data = run.train_from_id(10001)
stack_detector_data(train_data, 'image.data')

(2)
AttributeError                            Traceback (most recent call last)
<ipython-input-16-0e4738527f59> in <module>()
----> 1 modules_data = stack_detector_data(train_data, 'image.data')

/software/anaconda3/5.2/lib/python3.6/site-packages/karabo_data/reader.py in stack_detector_data(train, data, axis, modules, only, xcept)
   1119     modno_arrays = {}
   1120     for device in devices:
-> 1121         modno = int(re.search(r'/DET/(\d+)CH', device).group(1))
   1122         array = train[device][data]
   1123         dtypes.add(array.dtype)

AttributeError: 'NoneType' object has no attribute 'group'

(3)
https://www.cxidb.org/browse.html

**Comment by takluyver** [comment]
That's a rather unhelpful error message from `stack_detector_data` being given data that includes non-detector sources. There are a number of options to avoid that:

1. Use the new LPD/AGIPD data interfaces described here: https://karabo-data.readthedocs.io/en/latest/lpd_data.html

```python
lpd = LPD1M(run)
modules_data = lpd.get_array('image.data')
```

2. Select only the detector sources from the run:

```python
sel = run.select("*/DET/*")
tid, train_data = sel.train_from_id(10001)
modules_data = stack_detector_data(train_data, 'image.data')
```

3. Ask the function to select data based on a substring match: `stack_detector_data(train_data, 'image.data', only="/DET/")`
4. Ask the function to exclude other sources using the `xcept=` parameter. This is the most awkward, because you have to name every non-detector source.

Options 1 and 2 should have better performance, because they avoid loading data you're not interested in. We might deprecate options 3 and 4 at some point now that there are more powerful ways to do the same thing.

**Comment by takluyver** [comment]
Made PR #124 to make a better error message

**Comment by Calpas** [comment]
Dear Takluyver,
ok, thank you for your answer.
Regards
