### ISSUE TITLE
stack_detector_data failed to get AGIPD1M image.data

### ISSUE THREAD

**Issue by Calpas** [European-XFEL/karabo_data#136]
Dear experts,
- when I run "stack_detector_data" (1) on lpd it works fine, but when I run it on agipd, it does not find the "image.data" parameter (2). 
- I check that "image.data" exist in train_data. Do you see what is wrong?
Regards

(1)
sel = run.select("*/DET/*")
tid, train_data = sel.train_from_id(76988842)
modules_data = stack_detector_data(train_data, 'image.data')

(2)
KeyError                                  Traceback (most recent call last)
<ipython-input-77-5df0ac067dbe> in <module>
      3 #tid, train_data = sel.train_from_id(10002)
      4 
----> 5 modules_data = stack_detector_data(train_data, 'image.data')
      6 
      7 modules_data.shape

/gpfs/exfel/sw/software/xfel_anaconda3/1.0/lib/python3.7/site-packages/karabo_data-0.3.0-py3.7.egg/karabo_data/reader.py in stack_detector_data(train, data, axis, modules, only, xcept)
   1120     for device in devices:
   1121         modno = int(re.search(r'/DET/(\d+)CH', device).group(1))
-> 1122         array = train[device][data]
   1123         dtypes.add(array.dtype)
   1124         shapes.add(array.shape)

KeyError: 'image.data'

**Comment by antarcticrainforest** [comment]
Hey,

could you quickly let us know which run you're looking at?

**Comment by Calpas** [comment]
Yes, sorry. I'm looking at this directory: /beegfs/desy/group/it/ReferenceData/cxidb/ID-83/proc/r0250/

**Comment by antarcticrainforest** [comment]
Ok the problem is as you might have already guessed that there are some missing modules and we decided not to provide a solution for issues of that sort in ```stack_detector_data```. I'd suggest you'll take an alternative road and use ```karabo_data.components``` (https://karabo-data.readthedocs.io/en/latest/agipd_lpd_data.html?highlight=components#module-karabo_data.components) - as you're dealing with AGIPD data anyway. Here is a snipped that should be working:

```
import karabo_data as kd
from karabo_data.components import AGIPD1M 
run = kd.RunDirectory('/beegfs/desy/group/it/ReferenceData/cxidb/ID-83/proc/r0250')
sel = run.select('*/DET/*')
tid = 76988842
agipd = AGIPD1M(sel.select_trains(kd.by_id[tid:tid+1]))
data = agipd.get_array('image.data')
<xarray.DataArray (module: 16, train: 1, pulse: 64, slow_scan: 512, fast_scan: 128)>
array([[[[[ -0.442945, ...,  54.40852 ],
          ...,
          [  0.49517 , ...,   1.664861]],

         ...,

         [[ -6.782094, ..., -29.75864 ],
          ...,
          [ -0.763095, ..., -10.010621]]]],



       ...,



       [[[[       nan, ...,        nan],
          ...,
          [       nan, ...,        nan]],

         ...,

         [[       nan, ...,        nan],
          ...,
          [       nan, ...,        nan]]]]])
          [       nan, ...,        nan]]]]])

Coordinates:
  * pulse    (pulse) uint64 0 1 4 5 8 9 12 13 ... 113 116 117 120 121 124 125
  * train    (train) uint64 76988842
  * module   (module) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
Dimensions without coordinates: slow_scan, fast_scan

 ```
```data``` is of handy type xarray -> http://xarray.pydata.org/en/stable/. You can access the dimension variables by data.train, data.module, data.pulse and of course the data itself by data.values.

I hope that helps!

**Comment by Calpas** [comment]
Yes it help, thank you.

**Comment by valmar** [comment]
I have the same problem using stack_detector_data, but the error is different. Here is what I do:

data_coll = karabo_data.RunDirectory('/gpfs/exfel/exp/SPB/201802/p002166/raw/r0067/')                                                                            
tid, train_data=data_coll.train_from_id(57438693)                                                                                                                
data_stack=karabo_data.reader.stack_detector_data(train_data, 'image.data') 

I am following the example here: https://karabo-data.readthedocs.io/en/latest/apply_geometry.html 
At line [5]

This is what I get:

```
In [38]: data_stack=karabo_data.reader.stack_detector_data(train_data, 'image.data')                                                                                               
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-d979228d6da1> in <module>
----> 1 data_stack=karabo_data.reader.stack_detector_data(train_data, 'image.data')

/gpfs/cfel/cxi/scratch/user/vmariani/conda/envs/onda_development_karabo/lib/python3.7/site-packages/karabo_data/reader.py in stack_detector_data(train, data, axis, modules, only, xcept)
   1245     modno_arrays = {}
   1246     for device in devices:
-> 1247         modno = int(re.search(r'/DET/(\d+)CH', device).group(1))
   1248         array = train[device][data]
   1249         dtypes.add(array.dtype)
```

I would need to access only a few trains of the run

**Comment by takluyver** [comment]
@valmar I think you're running into issue #123.  Copying in my comment from there:

-----

That's a rather unhelpful error message (recently improved) from `stack_detector_data` being given data that includes non-detector sources. There are a number of options to avoid that:

1. Use the new LPD/AGIPD data interfaces described here: https://karabo-data.readthedocs.io/en/latest/lpd_data.html

```python
lpd = LPD1M(run)
modules_data = lpd.get_array('image.data')
```

2. Select only the detector sources from the run:

```python
sel = run.select("*/DET/*")
tid, train_data = sel.train_from_id(10001)
modules_data = stack_detector_data(train_data, 'image.data')
```

3. Ask the function to select data based on a substring match: `stack_detector_data(train_data, 'image.data', only="/DET/")`
4. Ask the function to exclude other sources using the `xcept=` parameter. This is the most awkward, because you have to name every non-detector source.

Options 1 and 2 should have better performance, because they avoid loading data you're not interested in. We might deprecate options 3 and 4 at some point now that there are more powerful ways to do the same thing.

**Comment by takluyver** [comment]
Testing this with your example, if you go for option 2, you will then run into the problem this thread is about. So I'd recommend you go for option 1. :slightly_smiling_face:

**Comment by Calpas** [comment]
Dear Takluyver,
ok, thank you.
Regards

**Comment by valmar** [comment]
@takluyver ok, I managed to select a train with option 1 like this:

```
data_coll = karabo_data.RunDirectory('/gpfs/exfel/exp/SPB/201802/p002166/raw/r0067/') 
train = data_coll.select_trains(karabo_data.by_id[[57440122,]])
agipd = karabo_data.components.AGIPD1M(train)
modules_data = agipd.get_array('image.data') 
```
modules_data.shape returns for me: (16, 1, 176, 2, 512, 128)
16 is clearly the modules, 176 is the frames, 2 is analog/digital, 512 and 128 are x and y, but what is the 1 in second place?

**Comment by takluyver** [comment]
1 train. This is a labelled array, so you can do `modules_data.dims` to see the axis labels.

**Comment by valmar** [comment]
Perfect, thank you!

**Comment by valmar** [comment]
I think 2. is better for me because with 1. I get the data for the full 
run, right?

Thank you for looking into this....

Valerio

**Comment by valmar** [comment]
Ok, but how can I then get the data for a single train?

**Comment by antarcticrainforest** [comment]
I think your code snippet from above works perfectly fine.

```
train = run.select_trains(by_id[[57440122,]]) 
agipd = AGIPD1M(train) 
modules_data = agipd.get_array('image.data') 
module_data
<xarray.DataArray (module: 16, train: 1, pulse: 176, data_gain: 2, slow_scan: 512, fast_scan: 128)
```
