### ISSUE TITLE
Command naming

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/karabo_data#22]
I've renamed the repository, the package and the docs to `karabo_data`.

The command line interface is still called `lsxfel`. Do we want to change this as well?

We also have some bits of earlier code in scripts called `euxfel_h5tool` and `euxfel_h5tool_tmp.py` - it looks like this wasn't fully implemented. Do we want to keep any of that code? If we want to record our intention to implement some features, I think issues are a more natural way to do that than stub code.

**Comment by tmichela** [comment]
I would like to remove these scripts. For the `lsxfel` I would keep it for now unless you have a good name (the command could be extended in the future and handle various format from different facility, the name would still be relevant).

**Comment by fangohr** [comment]
Convert to CBF: I think the ability to execute conversions from the command line is useful, and will be much more convenient for users than having to write a 3 line script to then execute (or type commands at prompt). 

I could imagine that we have command line options that match (selected) function names that carry out such operations, so that the command line options are defined through the name of the function that does the work. Might need exploring to see if this is effective or awkward.

Iterating over pulses and displaying images: yes, let's not hardcode this for now, and explore doing this from Python.

Agree with everything else - please proceed and remove the files.
